url: "https://needscallouts.com"        # the base hostname & protocol for the site, e.g. http://example.com
baseurl: ""                             # the subpath of the site, e.g. /blog
title: "Needs Callouts FC"              # the name of your site, e.g. ACME Corp.